### ISSUE TITLE
Esecutivo

### ISSUE THREAD

**Issue by gpasqualetti** [ai-sf/ai-sf.github.io#4]
Inserire descrizioni e foto del nuovo EC.

**Comment by philosophysics** [comment]
manca solo marianna e le ho inivato un reminder

**Comment by gpasqualetti** [comment]
Mancano anche alcune foto

Il 27 maggio 2016 18:33:07 CEST, philosophysics notifications@github.com ha scritto:

**Comment by gpasqualetti** [comment]
Qui tutto ok, chiudo.
