### ISSUE TITLE
Metatag

### ISSUE THREAD

**Issue by gpasqualetti** [ai-sf/ai-sf.github.io#9]
Aggiungere i metatag e gli og di facebook e twitter per pagine e i post in modo da migliorare il SEO e rendere gradevole la vista di condivisione sui social.

**Comment by Foelering** [comment]
se ora si aggiunge un'immagine x.png in img/thumbnails e si imposta "thumbnail: x.png" in un post, questa compare su facebook quando si condivide il blog. Testato con welcome to jekyll

**Comment by gpasqualetti** [comment]
Puoi guardare anche il sorgente della [home di ICPS2017](https://github.com/ICPS2017/icps2017.github.io/blob/master/index.html) per capire quali altri metatag aggiungere

**Comment by Foelering** [comment]
Metatag ci sono e sembrano funzionare. Si potrebbe voler cambiare il formato, ma è un'altra questione.

Per ora chiudo ^^
